[package]
name = "crab-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
once_cell = "1.0"
async-process = "1.4"

[build-dependencies]
gtk = { version = "0.4", package = "gtk4" }
